version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: crm_nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        user: 1000:1000
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - db
        container_name: crm_app
    artisan:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        working_dir: /var/www
        entrypoint: ['/var/www/artisan']
        container_name: crm_artisan
    composer:
        image: composer:latest
        volumes:
            - ./:/var/www
        working_dir: /var/www
        container_name: crm_composer

    npm:
        image: node:20.9-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: ['npm']
        container_name: crm_npm
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: homework-tracker
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        container_name: crm_db
